### ISSUE TITLE
Just what I was looking for!

### ISSUE THREAD

**Issue by DeastinY** [lrusak/shairport-display-qt#1]
Would love to jump in and add some documentation while I set this up ;)
Do you have anything prepped and simply not committed just yet, or should I go wild?

**Comment by lrusak** [comment]
@DeastinY Hey! Thanks for the interest.

I do have some plans to update the documention in regards to the setup that I run with my RPi3 and touchscreen. I also want to add more pythonic documentation regarding how to install and use this and the python requirements.txt

I also need to update the screenshot as the screenshot is from https://github.com/lrusak/shairport-display

If you have any questions though please ask here and I'll do my best to answer them.

**Comment by lrusak** [comment]
I've updated the screenshot and readme.
